/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      // design/tokens/design-tokens.json 과 1:1로 유지할 것.
      colors: {
        base: '#0b0f16',
        surface: '#131a26',
        'surface-raised': '#1c2433',
        primary: '#f4f7fb',
        secondary: '#c7cedb',
        muted: '#98a2b5',
        inverse: '#ffffff',
        accent: { DEFAULT: '#5b93f5', strong: '#2f5fc4' },
        success: { DEFAULT: '#3ddc97', strong: '#1f9d6b' },
        warning: { DEFAULT: '#f5b642', strong: '#b9861f' },
        danger: { DEFAULT: '#ff7a7a', strong: '#bf3939' },
      },
      backgroundColor: {
        base: '#0b0f16',
        surface: '#131a26',
        'surface-raised': '#1c2433',
        accent: { DEFAULT: '#5b93f5', strong: '#2f5fc4' },
        success: { DEFAULT: '#3ddc97', strong: '#1f9d6b' },
        warning: { DEFAULT: '#f5b642', strong: '#b9861f' },
        danger: { DEFAULT: '#ff7a7a', strong: '#bf3939' },
      },
      textColor: {
        primary: '#f4f7fb',
        secondary: '#c7cedb',
        muted: '#98a2b5',
        inverse: '#ffffff',
        accent: { DEFAULT: '#5b93f5', strong: '#2f5fc4' },
        success: { DEFAULT: '#3ddc97', strong: '#1f9d6b' },
        warning: { DEFAULT: '#f5b642', strong: '#b9861f' },
        danger: { DEFAULT: '#ff7a7a', strong: '#bf3939' },
      },
      borderColor: {
        DEFAULT: '#2b3444',
        default: '#2b3444',
        strong: '#5a6684',
        accent: '#5b93f5',
        success: '#3ddc97',
        warning: '#f5b642',
        danger: '#ff7a7a',
      },
      ringColor: {
        DEFAULT: '#5b93f5',
        accent: '#5b93f5',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"Apple SD Gothic Neo"',
          'Pretendard',
          '"SF Pro Text"',
          '"SF Pro Display"',
          '"Segoe UI"',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        mono: ['"SF Mono"', '"JetBrains Mono"', 'ui-monospace', 'Menlo', 'monospace'],
      },
      fontSize: {
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        body: ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-strong': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        subtitle: ['16px', { lineHeight: '24px', fontWeight: '500' }],
        section: ['20px', { lineHeight: '28px', fontWeight: '700' }],
        title: ['24px', { lineHeight: '32px', fontWeight: '800' }],
        metric: ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.01em' }],
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
      boxShadow: {
        card: '0 1px 2px rgba(0,0,0,0.4), 0 8px 24px -4px rgba(0,0,0,0.35)',
        raised: '0 4px 16px -2px rgba(0,0,0,0.5)',
      },
    },
  },
  plugins: [],
}
